# Deploy Markdown-as-HTML to GitHub Pages (keeps folder structure under /docs)
name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build docs folder (convert .md → .html, preserve structure)
        shell: bash
        run: |
          set -euo pipefail

          # 1) Start clean
          rm -rf docs
          mkdir -p docs

          # 2) Copy everything (except .git, .github, existing docs) into docs/
          rsync -a \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'docs/' \
            ./ docs/

          # 3) Convert every .md inside docs/ to .html (same paths)
          while IFS= read -r -d '' md; do
            html="${md%.md}.html"
            # Use GitHub-Flavored Markdown -> HTML5, standalone pages
            pandoc -f gfm -t html5 -s "$md" -o "$html" -c /assets/site.css
          done < <(find docs -type f -name '*.md' -print0)

          # 4) Optional: if there's a README at the root, make it the landing page
          if [[ -f "docs/README.html" && ! -f "docs/index.html" ]]; then
            cp docs/README.html docs/index.html
          fi

          # 5) Remove .md files from the built docs/ tree (we only want HTML + assets)
          find docs -type f -name '*.md' -delete

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs" # publish only the generated site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
