# Deploy Markdown-as-HTML to GitHub Pages (keeps folder structure under /docs)
name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build docs folder (convert .md → .html, preserve structure)
        shell: bash
        run: |
          set -euo pipefail

          # 0) Clean output
          rm -rf docs
          mkdir -p docs

          # 1) Copy everything except git metadata and existing docs
          rsync -a \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'docs/' \
            ./ docs/

          # 2) Convert every .md under docs/ to HTML, using a RELATIVE css path
          #    (assets/site.css must exist at repo root so rsync put it at docs/assets/site.css)
          while IFS= read -r -d '' md; do
            html="${md%.md}.html"
            pandoc -f gfm -t html5 -s "$md" -o "$html" -c assets/site.css
          done < <(find docs -type f -name '*.md' -print0)

          # 3) Optional landing page
          if [[ -f "docs/README.html" && ! -f "docs/index.html" ]]; then
            cp docs/README.html docs/index.html
          fi

          # 4) Remove markdown sources
          find docs -type f -name '*.md' -delete

          # 5) Sanity check in logs
          echo "Expect to find: docs/assets/site.css"; ls -l docs/assets/site.css || true
          echo "Sample HTML head:"; head -n 12 "$(find docs -type f -name '*.html' | head -n 1)"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs" # publish only the generated site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
