name: GitHub Pages

on:
  push:
    branches:
      - master # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install marked (for markdown conversion)
        run: npm install marked

      - name: Create docs structure
        run: |
          mkdir -p docs/guidelines docs/process

      - name: Convert Markdown to HTML
        run: |
          node -e "
          const fs = require('fs');
          const marked = require('marked');
          const path = require('path');

          // Function to convert markdown file to HTML
          function convertToHtml(mdPath, targetPath) {
            const md = fs.readFileSync(mdPath, 'utf-8');
            const html = marked.parse(md);
            const template = fs.readFileSync('docs/template.html', 'utf-8');
            fs.writeFileSync(targetPath, template.replace('{{content}}', html));
          }

          // Create template.html
          fs.writeFileSync('docs/template.html', \`
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset='UTF-8'>
              <meta name='viewport' content='width=device-width, initial-scale=1.0'>
              <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.2.0/github-markdown.min.css'>
              <style>
                .markdown-body {
                  box-sizing: border-box;
                  min-width: 200px;
                  max-width: 980px;
                  margin: 0 auto;
                  padding: 45px;
                }
                @media (max-width: 767px) {
                  .markdown-body {
                    padding: 15px;
                  }
                }
                .nav-back {
                  padding: 1rem;
                  background: #f6f8fa;
                  margin-bottom: 2rem;
                  border-radius: 6px;
                }
                .nav-back a {
                  color: #0366d6;
                  text-decoration: none;
                }
                .nav-back a:hover {
                  text-decoration: underline;
                }
              </style>
            </head>
            <body class='markdown-body'>
              <div class='nav-back'>
                <a href='..'>← Back to Guidelines</a>
              </div>
              {{content}}
            </body>
          </html>
          \`);

          // Copy original markdown files to docs
          const guidelinesFiles = fs.readdirSync('guidelines');
          guidelinesFiles.forEach(file => {
            if (file.endsWith('.md')) {
              fs.copyFileSync(
                \`guidelines/\${file}\`,
                \`docs/guidelines/\${file}\`
              );
              convertToHtml(
                \`guidelines/\${file}\`,
                \`docs/guidelines/\${file.replace('.md', '.html')}\`
              );
            }
          });

          const processFiles = fs.readdirSync('process');
          processFiles.forEach(file => {
            if (file.endsWith('.md')) {
              fs.copyFileSync(
                \`process/\${file}\`,
                \`docs/process/\${file}\`
              );
              convertToHtml(
                \`process/\${file}\`,
                \`docs/process/\${file.replace('.md', '.html')}\`
              );
            }
          });
          "

      - name: Copy index.html to docs
        run: |
          cp index.html docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: true
